apiVersion: v1
kind: Service
metadata:
  namespace: bingo
  name: bingo-java-service
spec:
  ports:
    - port: 80
      targetPort: 9090
      protocol: TCP
  type: ClusterIP
  selector:
    app: bingo-java