apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-trace
  namespace: opentelemetry-operator-system
spec:
  mode: deployment
  serviceAccount: adot-collector
  resources:
    #limits:
    #  cpu: 500m
    #  memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  config: |
    extensions:
      sigv4auth:
        region: "ap-southeast-1"
        service: "aps"
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
        timeout: 30s
        send_batch_size: 8192
      batch/metrics:
        timeout: 60s

    exporters:
      awsxray:
        region: "ap-southeast-1"

    service:
      telemetry:
        logs:
          level: "DEBUG"
      extensions: [sigv4auth]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [awsxray]