apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: sidecar
  namespace: {namespace}
spec:
  mode: sidecar
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
    exporters:
      logging:
      otlphttp:
        endpoint: "otel-trace-collector.opentelemetry-operator-system:4318"
        tls:
          insecure_skip_verify: true
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [otlphttp]
        metrics: # This is the new metrics pipeline
          receivers: [otlp]
          processors: []
          exporters: [otlphttp]

