apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: java-instrumentation
  namespace: opentelemetry-operator-system
spec:
  exporter:
    endpoint: http://otel-trace-collector.opentelemetry-operator-system:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  java:
    env:
    - name: OTEL_METRICS_EXPORTER
      value: none
    - name: OTEL_PROPAGATORS
      value: "xray"
    - name: OTEL_IGNORE_MODULES
      value: "fs"

