apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'x-ray-services'
  namespace: argocd
spec:
  destination:
    namespace: 'myapp'
    server: 'https://kubernetes.default.svc'
  source:
    path: 'x-ray'
    repoURL: 'https://jerrylam123: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@github.com/jerrylam123/bingo-uat.git'
    targetRevision: HEAD
  project: 'default'

  syncPolicy:
    syncOptions:
    - Createnamespace=true

    automated:
      selfHeal : true
      prune: true
