apiVersion: v1
kind: Service
metadata:
  name: bingo-rabbitmq-service
  namespace: bingo
spec:
  selector:
    app: bingo-rabbitmq
  ports:
    - name: port-5671
      protocol: TCP
      port: 81
      targetPort: 5671
    - name: port-5672
      protocol: TCP
      port: 82
      targetPort: 5672
    - name: port-15671
      protocol: TCP
      port: 83
      targetPort: 15671
    - name: port-15672
      protocol: TCP
      port: 80
      targetPort: 15672
    - name: port-4369
      protocol: TCP
      port: 84
      targetPort: 4369
    - name: port-25672
      protocol: TCP
      port: 85
      targetPort: 25672
  type: ClusterIP  # Change to "LoadBalancer" if you are using a cloud provider that supports it